# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2bb145f9a652bb1ca8f737c8c80ab0bc1d4103a0545929a787123c65b55b20e595881c6c636260bdd18ea7b1490f28db24ccaf6e753c69712a1d7294e0f0322

test:
  secret_key_base: 331bbcd4fcb42ca2822a638c8c12c496541e132fe3d0091bbb2f1658962918e992766b7691069e4075b1912709774c38ce27fa8a809ea43caed95e4e80a64a55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
